#!/usr/bin/env python
"""Dead-binding audit for the ecc_py binding census (--ecc-root).

Parses the ecc wrapper (``chipcompiler/tools/ecc/module.py`` in the outer
repo, read-only) with :mod:`ast`, classifies every ``self.ecc.<name>(`` call
against the census as active / disabled (file:line) / absent, and renders
``dead_bindings.md``.
"""
import ast
from pathlib import Path


def audit_wrapper(module_py: Path, discovery: dict) -> dict:
    """Parse the ecc wrapper module and classify every ``self.ecc.<name>(`` call.

    Returns a structured audit: per-method call rows, the dead-method
    candidates (every call disabled or absent), and methods with no calls.
    """
    tree = ast.parse(module_py.read_text())
    wrapper_class = next(
        (node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == "ECCToolsModule"),
        None,
    )
    if wrapper_class is None:
        raise ValueError(f"ECCToolsModule class not found in {module_py}")
    status_by_name: dict[str, str] = {}
    for binding in discovery["bindings"]:
        label = (
            "active"
            if binding.status_in_source == "active"
            else f"disabled ({binding.file}:{binding.line})"
        )
        previous = status_by_name.get(binding.py_name)
        if previous is None or (previous.startswith("disabled") and binding.status_in_source == "active"):
            status_by_name[binding.py_name] = label
    rows: list[dict] = []
    dead: list[str] = []
    without_calls: list[str] = []
    for node in wrapper_class.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        calls: list[dict] = []
        seen: set[str] = set()
        for sub in ast.walk(node):
            if (
                isinstance(sub, ast.Call)
                and isinstance(sub.func, ast.Attribute)
                and isinstance(sub.func.value, ast.Attribute)
                and sub.func.value.attr == "ecc"
                and isinstance(sub.func.value.value, ast.Name)
                and sub.func.value.value.id == "self"
            ):
                name = sub.func.attr
                if name in seen:
                    continue
                seen.add(name)
                calls.append({"binding": name, "status": status_by_name.get(name, "absent")})
        if not calls:
            without_calls.append(node.name)
            continue
        rows.append({"method": node.name, "line": node.lineno, "calls": calls})
        if all(call["status"] != "active" for call in calls):
            dead.append(node.name)
    return {
        "rows": rows,
        "dead_method_candidates": sorted(dead),
        "methods_without_calls": sorted(without_calls),
    }


LIST_NONE_AUDIT = """\
## List-element `None` audit

Today the wrapper normalizes list arguments with `path_texts()`
(`chipcompiler/utility/path.py`), which silently drops `None` elements. After
the `std::vector<std::filesystem::path>` conversion a `None` element raises
`TypeError` instead. The lists reaching `db_init` / `lef_init` / `lib_init`
were traced through every producer in `chipcompiler/tools/ecc/module.py` and
its callers:

- `init_lefs(workspace.pdk.lefs)` (`runner.py`): `pdk.lefs` is built in
  `chipcompiler/data/pdk.py` as `[path for path in lef_paths if path.is_file()]`
  — a list of existing `Path` objects; elements are never `None`.
- `run_timing(lib_paths=...)` (`runner.py`): receives `workspace.pdk.libs`
  (same filtered `Path` list construction) and validates every element with
  `os.path.isfile` before the call; `module.py` itself coerces a `None` *list*
  to `[]` (`if lib_paths is None: lib_paths = []`).
- `write_timing_model(lib_paths=signoff_item["liberty_files"])` (`runner.py`):
  `collect_sta_signoff_items` reads `liberty.get("path", [])` from the sta
  config JSON — a JSON array of strings. The parallel `run_sta` flow validates
  the same list with `os.path.exists` per element, which already raises
  `TypeError` on a `null` element before any binding call.
- `update_sta_data_config(lib_paths=...)`: only exercised by tests with real
  `Path` lists.

Conclusion: `None` *elements* cannot occur in any current producer — the only
`None` value in play is the list argument itself, which `module.py` already
coerces to `[]` before calling `path_texts`. A hand-edited sta config JSON
with a `null` array element is the only theoretical injection point; there the
conversion changes a silent drop into a loud `TypeError`, which is the desired
behavior.
"""


def render_dead_bindings_md(audit: dict) -> str:
    lines = [
        "# Dead-binding audit",
        "",
        "Generated by `binding_census.py --ecc-root` from the ecc wrapper "
        "(`chipcompiler/tools/ecc/module.py`) joined against the binding "
        "census. Regenerate with:",
        "",
        "```sh",
        "uv run --no-project --with jsonschema python scripts/binding_census/binding_census.py \\",
        "  --ecc-root <path-to-ecc-repo>",
        "```",
        "",
        "Statuses: `active` = bound and registered in `ecc_py`; "
        "`disabled (file:line)` = an `m.def` exists but is commented out or its "
        "register function is never called; `absent` = no `m.def` anywhere in "
        "the `ecc_py` census (the call would raise `AttributeError` at runtime). "
        "Note that a sibling native module (e.g. `ipower_cpp`, built from "
        "`src/operation/refactor`) may bind the same name under a different "
        "Python module; that does not make the `ecc_py` call live.",
        "",
        "| Wrapper method | Called binding | Status |",
        "|---|---|---|",
    ]
    for row in audit["rows"]:
        for call in row["calls"]:
            lines.append(f"| `{row['method']}` | `{call['binding']}` | {call['status']} |")
    lines += [
        "",
        "## Dead-method candidates",
        "",
        "Wrapper methods whose every `ecc_py` call is disabled or absent:",
        "",
    ]
    for name in audit["dead_method_candidates"]:
        lines.append(f"- `{name}`")
    lines += [
        "",
        "## Wrapper methods with no `ecc_py` calls",
        "",
        "Informational only (stubs or pure-Python helpers; not evaluated by the "
        "disabled/absent rule):",
        "",
    ]
    for name in audit["methods_without_calls"]:
        lines.append(f"- `{name}`")
    lines += ["", LIST_NONE_AUDIT.strip(), ""]
    return "\n".join(lines)
