// ***************************************************************************************
// Copyright (c) 2023-2025 Peng Cheng Laboratory
// Copyright (c) 2023-2025 Institute of Computing Technology, Chinese Academy of Sciences
// Copyright (c) 2023-2025 Beijing Institute of Open Source Chip
//
// iEDA is licensed under Mulan PSL v2.
// You can use this software according to the terms and conditions of the Mulan PSL v2.
// You may obtain a copy of Mulan PSL v2 at:
// http://license.coscl.org.cn/MulanPSL2
//
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
// EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
// MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
//
// See the Mulan PSL v2 for more details.
// ***************************************************************************************

#define GLOG_NO_ABBREVIATED_SEVERITIES
#include "py_register_imp.h"

#include <pybind11/cast.h>

#include "idb_to_imp_db/PyPlaceDB.h"

namespace python_interface {
namespace py = pybind11;

void register_imp(pybind11::module& m)
{
  pybind11::class_<PyPlaceDB>(m, "PyPlaceDB")
      .def("getCongestionMap", &PyPlaceDB::getCongestionMap, py::arg("method") = "max", py::arg("stage") = "egr3D", py::arg("resolve_congestion") = "low")
      .def("write_macro_placement_back", &PyPlaceDB::writeMacroPlacementBack, py::arg("node_x"), py::arg("node_y"))
      .def("apply_sizing", &PyPlaceDB::applySizing, py::arg("cell_ids"), py::arg("target_master_names"))
      .def("apply_buffer_actions", &PyPlaceDB::applyBufferActions, py::arg("actions"), py::arg("action_digest"))
      .def_readwrite("num_nodes", &PyPlaceDB::num_nodes)
      .def_readwrite("num_terminals", &PyPlaceDB::num_terminals)
      .def_readwrite("num_terminal_NIs", &PyPlaceDB::num_terminal_NIs)
      .def_readwrite("m2_pg_rail_blockage_rects", &PyPlaceDB::m2_pg_rail_blockage_rects)
      .def_readwrite("m2_pg_rail_boxes", &PyPlaceDB::m2_pg_rail_boxes)
      .def_readwrite("m2_pg_rail_density_boxes", &PyPlaceDB::m2_pg_rail_density_boxes)
      .def_readwrite("node_name2id_map", &PyPlaceDB::node_name2id_map)
      .def_readwrite("node_names", &PyPlaceDB::node_names)
      .def_readwrite("node_x", &PyPlaceDB::node_x)
      .def_readwrite("node_y", &PyPlaceDB::node_y)
      .def_readwrite("node_orient", &PyPlaceDB::node_orient)
      .def_readwrite("node_size_x", &PyPlaceDB::node_size_x)
      .def_readwrite("node_size_y", &PyPlaceDB::node_size_y)
      .def_property_readonly("node_is_hard_macro", &PyPlaceDB::getNodeIsHardMacro)
      .def_property_readonly("macro_writeback_candidate", &PyPlaceDB::getMacroWritebackCandidate)
      .def_readwrite("node2orig_node_map", &PyPlaceDB::node2orig_node_map)
      .def_readwrite("pin_direct", &PyPlaceDB::pin_direct)
      .def_readwrite("pin_offset_x", &PyPlaceDB::pin_offset_x)
      .def_readwrite("pin_offset_y", &PyPlaceDB::pin_offset_y)
      .def_readwrite("pin_names", &PyPlaceDB::pin_names)
      .def_readwrite("net_name2id_map", &PyPlaceDB::net_name2id_map)
      // .def_readwrite("pin_name2id_map", &PyPlaceDB::pin_name2id_map)
      .def_readwrite("net_names", &PyPlaceDB::net_names)
      .def_readwrite("clock_net_names", &PyPlaceDB::clock_net_names)
      .def_readwrite("net2pin_map", &PyPlaceDB::net2pin_map)
      .def_readwrite("flat_net2pin_map", &PyPlaceDB::flat_net2pin_map)
      .def_readwrite("flat_net2pin_start_map", &PyPlaceDB::flat_net2pin_start_map)
      .def_readwrite("net_weights", &PyPlaceDB::net_weights)
      // .def_readwrite("net_weight_deltas", &PyPlaceDB::net_weight_deltas)
      // .def_readwrite("net_criticality", &PyPlaceDB::net_criticality)
      // .def_readwrite("net_criticality_deltas", &PyPlaceDB::net_criticality_deltas)
      .def_readwrite("node2pin_map", &PyPlaceDB::node2pin_map)
      .def_readwrite("flat_node2pin_map", &PyPlaceDB::flat_node2pin_map)
      .def_readwrite("flat_node2pin_start_map", &PyPlaceDB::flat_node2pin_start_map)
      .def_readwrite("regions", &PyPlaceDB::regions)
      .def_readwrite("flat_region_boxes", &PyPlaceDB::flat_region_boxes)
      .def_readwrite("flat_region_boxes_start", &PyPlaceDB::flat_region_boxes_start)
      .def_readwrite("node2fence_region_map", &PyPlaceDB::node2fence_region_map)
      .def_readwrite("pin2node_map", &PyPlaceDB::pin2node_map)
      .def_readwrite("pin2net_map", &PyPlaceDB::pin2net_map)
      .def_readwrite("timing_schema_version", &PyPlaceDB::timing_schema_version)
      .def_readwrite("timing_diagnostics", &PyPlaceDB::timing_diagnostics)
      .def_readwrite("timing_clock_names", &PyPlaceDB::timing_clock_names)
      .def_readwrite("timing_clock_info", &PyPlaceDB::timing_clock_info)
      .def_readwrite("timing_source_time_unit_ps", &PyPlaceDB::timing_source_time_unit_ps)
      .def_readwrite("timing_source_capacitance_unit_pf", &PyPlaceDB::timing_source_capacitance_unit_pf)
      .def_readwrite("timing_source_resistance_unit_ohm", &PyPlaceDB::timing_source_resistance_unit_ohm)
      .def_readwrite("timing_unit_provenance", &PyPlaceDB::timing_unit_provenance)
      .def_readwrite("timing_sdc_path", &PyPlaceDB::timing_sdc_path)
      .def_readwrite("timing_spef_path", &PyPlaceDB::timing_spef_path)
      .def_readwrite("timing_parasitics_initialization", &PyPlaceDB::timing_parasitics_initialization)
      .def_readwrite("start_points", &PyPlaceDB::start_points)
      .def_readwrite("end_points", &PyPlaceDB::end_points)
      .def_readwrite("endpoints_max_valid", &PyPlaceDB::endpoints_max_valid)
      .def_readwrite("endpoints_max_reason", &PyPlaceDB::endpoints_max_reason)
      .def_readwrite("endpoints_constraint_max_valid", &PyPlaceDB::endpoints_constraint_max_valid)
      .def_readwrite("endpoints_constraint_max_reason", &PyPlaceDB::endpoints_constraint_max_reason)
      .def_readwrite("endpoints_timing_check_max_valid", &PyPlaceDB::endpoints_timing_check_max_valid)
      .def_readwrite("endpoints_timing_check_max_reason", &PyPlaceDB::endpoints_timing_check_max_reason)
      .def_readwrite("clock_pins", &PyPlaceDB::clock_pins)
      .def_readwrite("FF_ids", &PyPlaceDB::FF_ids)
      .def_readwrite("clk_pin_r_aat", &PyPlaceDB::clk_pin_r_aat)
      .def_readwrite("clk_pin_f_aat", &PyPlaceDB::clk_pin_f_aat)
      .def_readwrite("clk_pin_rtran", &PyPlaceDB::clk_pin_rtran)
      .def_readwrite("clk_pin_ftran", &PyPlaceDB::clk_pin_ftran)
      .def_readwrite("clk_pin_names", &PyPlaceDB::clk_pin_names)
      .def_readwrite("inrdelays", &PyPlaceDB::inrdelays)
      .def_readwrite("infdelays", &PyPlaceDB::infdelays)
      .def_readwrite("inrtrans", &PyPlaceDB::inrtrans)
      .def_readwrite("inftrans", &PyPlaceDB::inftrans)
      .def_readwrite("outcaps", &PyPlaceDB::outcaps)
      .def_readwrite("endpoints_rRAT", &PyPlaceDB::endpoints_rRAT)
      .def_readwrite("endpoints_fRAT", &PyPlaceDB::endpoints_fRAT)
      .def_readwrite("backend_endpoint_rAAT", &PyPlaceDB::backend_endpoint_rAAT)
      .def_readwrite("backend_endpoint_fAAT", &PyPlaceDB::backend_endpoint_fAAT)
      .def_readwrite("backend_endpoint_rRAT", &PyPlaceDB::backend_endpoint_rRAT)
      .def_readwrite("backend_endpoint_fRAT", &PyPlaceDB::backend_endpoint_fRAT)
      .def_readwrite("backend_endpoint_rSlew", &PyPlaceDB::backend_endpoint_rSlew)
      .def_readwrite("backend_endpoint_fSlew", &PyPlaceDB::backend_endpoint_fSlew)
      .def_readwrite("backend_endpoint_min_rAAT", &PyPlaceDB::backend_endpoint_min_rAAT)
      .def_readwrite("backend_endpoint_min_fAAT", &PyPlaceDB::backend_endpoint_min_fAAT)
      .def_readwrite("backend_endpoint_min_rRAT", &PyPlaceDB::backend_endpoint_min_rRAT)
      .def_readwrite("backend_endpoint_min_fRAT", &PyPlaceDB::backend_endpoint_min_fRAT)
      .def_readwrite("net2driver_pin_map", &PyPlaceDB::net2driver_pin_map)
      .def_readwrite("net_flat_arcs_start", &PyPlaceDB::net_flat_arcs_start)
      .def_readwrite("net_flat_arcs", &PyPlaceDB::net_flat_arcs)
      .def_readwrite("inst_flat_arcs_start", &PyPlaceDB::inst_flat_arcs_start)
      .def_readwrite("inst_flat_arcs", &PyPlaceDB::inst_flat_arcs)
      .def_readwrite("flat_inst_arcs_by_level", &PyPlaceDB::flat_inst_arcs_by_level)
      .def_readwrite("flat_inst_arcs_by_level_start", &PyPlaceDB::flat_inst_arcs_by_level_start)
      .def_readwrite("flat_pin_to_graph", &PyPlaceDB::flat_pin_to_graph)
      .def_readwrite("flat_pin_to_graph_start", &PyPlaceDB::flat_pin_to_graph_start)
      .def_readwrite("flat_pin_to_graph_reverse", &PyPlaceDB::flat_pin_to_graph_reverse)
      .def_readwrite("flat_pin_to_graph_start_reverse", &PyPlaceDB::flat_pin_to_graph_start_reverse)
      .def_readwrite("pin_pair_arc_keys", &PyPlaceDB::pin_pair_arc_keys)
      .def_readwrite("flat_pin_pair_arc_start", &PyPlaceDB::flat_pin_pair_arc_start)
      .def_readwrite("flat_pin_pair_arc_indices", &PyPlaceDB::flat_pin_pair_arc_indices)
      .def_readwrite("arc_level_start", &PyPlaceDB::arc_level_start)
      .def_readwrite("arc_src_pin", &PyPlaceDB::arc_src_pin)
      .def_readwrite("arc_dst_pin", &PyPlaceDB::arc_dst_pin)
      .def_readwrite("arc_inst_id", &PyPlaceDB::arc_inst_id)
      .def_readwrite("arc_libcell_id", &PyPlaceDB::arc_libcell_id)
      .def_readwrite("arc_libarc_id", &PyPlaceDB::arc_libarc_id)
      .def_readwrite("arc_sense", &PyPlaceDB::arc_sense)
      .def_readwrite("arc_type", &PyPlaceDB::arc_type)
      .def_readwrite("arc_offset", &PyPlaceDB::arc_offset)
      .def_readwrite("pin_pred_start", &PyPlaceDB::pin_pred_start)
      .def_readwrite("pin_pred_pin", &PyPlaceDB::pin_pred_pin)
      .def_readwrite("pin_pred_arc_id", &PyPlaceDB::pin_pred_arc_id)
      .def_readwrite("pin_succ_start", &PyPlaceDB::pin_succ_start)
      .def_readwrite("pin_succ_pin", &PyPlaceDB::pin_succ_pin)
      .def_readwrite("pin_succ_arc_id", &PyPlaceDB::pin_succ_arc_id)
      .def_readwrite("endpoint_pin_ids", &PyPlaceDB::endpoint_pin_ids)
      .def_readwrite("start_pin_ids", &PyPlaceDB::start_pin_ids)
      .def_readwrite("pin_to_inst_id", &PyPlaceDB::pin_to_inst_id)
      .def_readwrite("pin_to_node_id", &PyPlaceDB::pin_to_node_id)
      .def_readwrite("inst_topo_start", &PyPlaceDB::inst_topo_start)
      .def_readwrite("inst_topo_ids", &PyPlaceDB::inst_topo_ids)
      .def_readwrite("endpoints_constraint_arcs", &PyPlaceDB::endpoints_constraint_arcs)
      .def_readwrite("endpoints_timing_check_arcs", &PyPlaceDB::endpoints_timing_check_arcs)
      .def_readwrite("flat_libcell_info", &PyPlaceDB::flat_libcell_info)
      .def_readwrite("buffer_main_type_index", &PyPlaceDB::buffer_main_type_index)
      .def_readwrite("buffer_main_type_status", &PyPlaceDB::buffer_main_type_status)
      .def_readwrite("buffer_main_type_candidate_indices", &PyPlaceDB::buffer_main_type_candidate_indices)
      .def_readwrite("flat_libcell_names", &PyPlaceDB::flat_libcell_names)
      .def_readwrite("flat_libcell_width", &PyPlaceDB::flat_libcell_width)
      .def_readwrite("flat_libcell_height", &PyPlaceDB::flat_libcell_height)
      .def_readwrite("flat_libcell_leakage", &PyPlaceDB::flat_libcell_leakage)
      .def_readwrite("flat_libcell_main_id2size_vt_limit", &PyPlaceDB::flat_libcell_main_id2size_vt_limit)
      .def_readwrite("main_id_is_sizeable", &PyPlaceDB::main_id_is_sizeable)
      .def_readwrite("main_id_2_cell_id_start", &PyPlaceDB::main_id_2_cell_id_start)
      .def_readwrite("inst_main_id", &PyPlaceDB::inst_main_id)
      .def_readwrite("inst_libcell_offset", &PyPlaceDB::inst_libcell_offset)
      .def_readwrite("cell_id_2_arc_id_start", &PyPlaceDB::cell_id_2_arc_id_start)
      .def_readwrite("cell_id_2_libpin_id_start", &PyPlaceDB::cell_id_2_libpin_id_start)
      .def_readwrite("pin_2_libpin_offset", &PyPlaceDB::pin_2_libpin_offset)
      .def_readwrite("flat_lib_pin_offset_x", &PyPlaceDB::flat_lib_pin_offset_x)
      .def_readwrite("flat_lib_pin_offset_y", &PyPlaceDB::flat_lib_pin_offset_y)
      .def_readwrite("flat_lib_pin_cap", &PyPlaceDB::flat_lib_pin_cap)
      .def_readwrite("flat_lib_pin_rcap", &PyPlaceDB::flat_lib_pin_rcap)
      .def_readwrite("flat_lib_pin_fcap", &PyPlaceDB::flat_lib_pin_fcap)
      .def_readwrite("flat_lib_pin_cap_limit", &PyPlaceDB::flat_lib_pin_cap_limit)
      .def_readwrite("flat_lib_pin_slew_limit", &PyPlaceDB::flat_lib_pin_slew_limit)
      .def_readwrite("flat_libarc_info", &PyPlaceDB::flat_libarc_info)
      .def_readwrite("f_delay_flat_luts_values", &PyPlaceDB::f_delay_flat_luts_values)
      .def_readwrite("f_delay_flat_luts_trans_table", &PyPlaceDB::f_delay_flat_luts_trans_table)
      .def_readwrite("f_delay_flat_luts_cap_table", &PyPlaceDB::f_delay_flat_luts_cap_table)
      .def_readwrite("f_delay_flat_luts_dim", &PyPlaceDB::f_delay_flat_luts_dim)
      .def_readwrite("r_delay_flat_luts_values", &PyPlaceDB::r_delay_flat_luts_values)
      .def_readwrite("r_delay_flat_luts_trans_table", &PyPlaceDB::r_delay_flat_luts_trans_table)
      .def_readwrite("r_delay_flat_luts_cap_table", &PyPlaceDB::r_delay_flat_luts_cap_table)
      .def_readwrite("r_delay_flat_luts_dim", &PyPlaceDB::r_delay_flat_luts_dim)
      .def_readwrite("f_trans_flat_luts_values", &PyPlaceDB::f_trans_flat_luts_values)
      .def_readwrite("f_trans_flat_luts_trans_table", &PyPlaceDB::f_trans_flat_luts_trans_table)
      .def_readwrite("f_trans_flat_luts_cap_table", &PyPlaceDB::f_trans_flat_luts_cap_table)
      .def_readwrite("f_trans_flat_luts_dim", &PyPlaceDB::f_trans_flat_luts_dim)
      .def_readwrite("r_trans_flat_luts_values", &PyPlaceDB::r_trans_flat_luts_values)
      .def_readwrite("r_trans_flat_luts_trans_table", &PyPlaceDB::r_trans_flat_luts_trans_table)
      .def_readwrite("r_trans_flat_luts_cap_table", &PyPlaceDB::r_trans_flat_luts_cap_table)
      .def_readwrite("r_trans_flat_luts_dim", &PyPlaceDB::r_trans_flat_luts_dim)
      .def_readwrite("c_unit", &PyPlaceDB::c_unit)
      .def_readwrite("r_unit", &PyPlaceDB::r_unit)
      .def_readwrite("rows", &PyPlaceDB::rows)
      .def_readwrite("xl", &PyPlaceDB::xl)
      .def_readwrite("yl", &PyPlaceDB::yl)
      .def_readwrite("xh", &PyPlaceDB::xh)
      .def_readwrite("yh", &PyPlaceDB::yh)
      .def_readwrite("row_height", &PyPlaceDB::row_height)
      .def_readwrite("site_width", &PyPlaceDB::site_width)
      .def_readwrite("total_fixed_node_area", &PyPlaceDB::total_fixed_node_area)
      .def_readwrite("total_space_area", &PyPlaceDB::total_space_area)
      .def_readwrite("num_movable_pins", &PyPlaceDB::num_movable_pins)
      .def_readwrite("num_routing_grids_x", &PyPlaceDB::num_routing_grids_x)
      .def_readwrite("num_routing_grids_y", &PyPlaceDB::num_routing_grids_y)
      .def_readwrite("routing_grid_xl", &PyPlaceDB::routing_grid_xl)
      .def_readwrite("routing_grid_yl", &PyPlaceDB::routing_grid_yl)
      .def_readwrite("routing_grid_xh", &PyPlaceDB::routing_grid_xh)
      .def_readwrite("routing_grid_yh", &PyPlaceDB::routing_grid_yh)
      .def_readwrite("unit_horizontal_capacities", &PyPlaceDB::unit_horizontal_capacities)
      .def_readwrite("unit_vertical_capacities", &PyPlaceDB::unit_vertical_capacities)
      .def_readwrite("min_wire_widths", &PyPlaceDB::min_wire_widths)
      .def_readwrite("min_wire_spacings", &PyPlaceDB::min_wire_spacings)
      .def_readonly("native_state_dirty", &PyPlaceDB::native_state_dirty)
      .def_readonly("native_mutation_epoch", &PyPlaceDB::native_mutation_epoch)
      .def_readwrite("initial_horizontal_demand_map", &PyPlaceDB::initial_horizontal_demand_map)
      .def_readwrite("initial_vertical_demand_map", &PyPlaceDB::initial_vertical_demand_map)
      .def_readwrite("dbu", &PyPlaceDB::dbu);

  m.def(
      "pydb",
      [](idm::DataManager* db, int numRoutingGridsX, int numRoutingGridsY, bool with_routability, bool with_sta,
         bool include_m2_pg_rail_blockage, bool include_m2_pg_rail_density) {
        return PyPlaceDB(db, numRoutingGridsX, numRoutingGridsY, with_routability, with_sta, include_m2_pg_rail_blockage,
                         include_m2_pg_rail_density);
      },
      py::arg("db"), py::arg("numRoutingGridsX"), py::arg("numRoutingGridsY"), py::arg("with_routability"), py::arg("with_sta"),
      py::arg("include_m2_pg_rail_blockage") = false, py::arg("include_m2_pg_rail_density") = true,
      "Convert PlaceDB to PyPlaceDB");
}

}  // namespace python_interface
