add_subdirectory(iDRC)
add_subdirectory(iFP)
add_subdirectory(iEMIR)
add_subdirectory(iRT)
add_subdirectory(iLVS)
add_subdirectory(iRCX)
add_subdirectory(iSTA)
add_subdirectory(iCTS)
add_subdirectory(iZH)

if(TARGET irt_early_router AND TARGET izh_interface)
    target_link_libraries(irt_early_router PUBLIC izh_interface)
endif()
