/* yosys_hierarchy_declaration */
/* Generated by Yosys 0.58+86 (git sha1 8bc63ef6d, g++ 12.3.0-17deepin15 -fPIC -O3) */

module GcdUnitCtrlRTL_0x4d0fc71ead8d3d9e(a_mux_sel, a_reg_en, b_mux_sel, b_reg_en, clk, is_a_lt_b, is_b_zero, req_rdy, req_val, reset, resp_rdy, resp_val);
  output [1:0] a_mux_sel;
  wire [1:0] a_mux_sel;
  output [0:0] a_reg_en;
  wire [0:0] a_reg_en;
  output [0:0] b_mux_sel;
  wire [0:0] b_mux_sel;
  output [0:0] b_reg_en;
  wire [0:0] b_reg_en;
  input [0:0] clk;
  wire [0:0] clk;
  input [0:0] is_a_lt_b;
  wire [0:0] is_a_lt_b;
  input [0:0] is_b_zero;
  wire [0:0] is_b_zero;
  output [0:0] req_rdy;
  wire [0:0] req_rdy;
  input [0:0] req_val;
  wire [0:0] req_val;
  input [0:0] reset;
  wire [0:0] reset;
  input [0:0] resp_rdy;
  wire [0:0] resp_rdy;
  output [0:0] resp_val;
  wire [0:0] resp_val;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] curr_state__0;
  wire [1:0] current_state__1;
  wire [1:0] next_state__0;
  wire [0:0] \state$clk ;
  wire [1:0] \state$in_ ;
  wire [1:0] \state$out ;
  wire [0:0] \state$reset ;
  sg13g2_inv_1 _04_ (
    .A(\state$out [1]),
    .Y(a_reg_en)
  );
  sg13g2_inv_1 _05_ (
    .A(is_a_lt_b),
    .Y(_00_)
  );
  sg13g2_nor2_1 _06_ (
    .A(\state$out [1]),
    .B(\state$out [0]),
    .Y(b_mux_sel)
  );
  sg13g2_nor2b_1 _07_ (
    .A(\state$out [1]),
    .B_N(\state$out [0]),
    .Y(_01_)
  );
  sg13g2_and2_1 _08_ (
    .A(is_a_lt_b),
    .B(_01_),
    .X(a_mux_sel[1])
  );
  sg13g2_a21oi_1 _09_ (
    .A1(\state$out [0]),
    .A2(_00_),
    .B1(\state$out [1]),
    .Y(b_reg_en)
  );
  sg13g2_nor2_1 _10_ (
    .A(a_reg_en),
    .B(\state$out [0]),
    .Y(resp_val)
  );
  sg13g2_and2_1 _11_ (
    .A(_00_),
    .B(_01_),
    .X(a_mux_sel[0])
  );
  sg13g2_nand3_1 _12_ (
    .A(_00_),
    .B(is_b_zero),
    .C(_01_),
    .Y(_02_)
  );
  sg13g2_a21oi_1 _13_ (
    .A1(a_reg_en),
    .A2(req_val),
    .B1(\state$out [0]),
    .Y(_03_)
  );
  sg13g2_a21oi_1 _14_ (
    .A1(is_b_zero),
    .A2(a_mux_sel[0]),
    .B1(_03_),
    .Y(\state$in_ [0])
  );
  sg13g2_a22oi_1 _15_ (
    .A1(resp_rdy),
    .A2(resp_val),
    .B1(_02_),
    .B2(a_reg_en),
    .Y(\state$in_ [1])
  );
  RegRst_0x9f365fdf6c8998a state (
    .clk(clk),
    .in_(\state$in_ ),
    .out(\state$out ),
    .reset(reset)
  );
  assign curr_state__0 = \state$out ;
  assign current_state__1 = \state$out ;
  assign next_state__0 = \state$in_ ;
  assign req_rdy = b_mux_sel;
  assign \state$clk  = clk;
  assign \state$reset  = reset;
endmodule

module GcdUnitDpathRTL_0x4d0fc71ead8d3d9e(a_mux_sel, a_reg_en, b_mux_sel, b_reg_en, clk, is_a_lt_b, is_b_zero, req_msg_a, req_msg_b, reset, resp_msg);
  input [1:0] a_mux_sel;
  wire [1:0] a_mux_sel;
  input [0:0] a_reg_en;
  wire [0:0] a_reg_en;
  input [0:0] b_mux_sel;
  wire [0:0] b_mux_sel;
  input [0:0] b_reg_en;
  wire [0:0] b_reg_en;
  input [0:0] clk;
  wire [0:0] clk;
  output [0:0] is_a_lt_b;
  wire [0:0] is_a_lt_b;
  output [0:0] is_b_zero;
  wire [0:0] is_b_zero;
  input [15:0] req_msg_a;
  wire [15:0] req_msg_a;
  input [15:0] req_msg_b;
  wire [15:0] req_msg_b;
  input [0:0] reset;
  wire [0:0] reset;
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  wire [0:0] \a_lt_b$clk ;
  wire [15:0] \a_lt_b$in0 ;
  wire [15:0] \a_lt_b$in1 ;
  wire [0:0] \a_lt_b$out ;
  wire [0:0] \a_lt_b$reset ;
  wire [0:0] \a_mux$clk ;
  wire [15:0] \a_mux$in_$000 ;
  wire [15:0] \a_mux$in_$001 ;
  wire [15:0] \a_mux$in_$002 ;
  wire [15:0] \a_mux$out ;
  wire [0:0] \a_mux$reset ;
  wire [1:0] \a_mux$sel ;
  wire [0:0] \a_reg$clk ;
  wire [0:0] \a_reg$en ;
  wire [15:0] \a_reg$in_ ;
  wire [15:0] \a_reg$out ;
  wire [0:0] \a_reg$reset ;
  wire [0:0] \b_mux$clk ;
  wire [15:0] \b_mux$in_$000 ;
  wire [15:0] \b_mux$in_$001 ;
  wire [15:0] \b_mux$out ;
  wire [0:0] \b_mux$reset ;
  wire [0:0] \b_mux$sel ;
  wire [0:0] \b_reg$clk ;
  wire [0:0] \b_reg$en ;
  wire [15:0] \b_reg$in_ ;
  wire [15:0] \b_reg$out ;
  wire [0:0] \b_reg$reset ;
  wire [15:0] b_reg_out;
  wire [0:0] \b_zero$clk ;
  wire [15:0] \b_zero$in_ ;
  wire [0:0] \b_zero$out ;
  wire [0:0] \b_zero$reset ;
  wire [0:0] \sub$clk ;
  wire [15:0] \sub$in0 ;
  wire [15:0] \sub$in1 ;
  wire [15:0] \sub$out ;
  wire [0:0] \sub$reset ;
  wire [15:0] sub_out;
  LtComparator_0x422b1f52edd46a85 a_lt_b (
    .clk(clk),
    .in0(\a_lt_b$in0 ),
    .in1(\a_lt_b$in1 ),
    .out(\a_lt_b$out ),
    .reset(reset)
  );
  Mux_0x683fa1a418b072c9 a_mux (
    .clk(clk),
    .\in_$000 (req_msg_a),
    .\in_$001 (\a_mux$in_$001 ),
    .\in_$002 (\a_lt_b$in1 ),
    .out(\a_mux$out ),
    .reset(reset),
    .sel(a_mux_sel)
  );
  RegEn_0x68db79c4ec1d6e5b a_reg (
    .clk(clk),
    .en(a_reg_en),
    .in_(\a_mux$out ),
    .out(\a_lt_b$in0 ),
    .reset(reset)
  );
  Mux_0xdd6473406d1a99a b_mux (
    .clk(clk),
    .\in_$000 (\a_lt_b$in0 ),
    .\in_$001 (req_msg_b),
    .out(\b_mux$out ),
    .reset(reset),
    .sel(b_mux_sel)
  );
  RegEn_0x68db79c4ec1d6e5b b_reg (
    .clk(clk),
    .en(b_reg_en),
    .in_(\b_mux$out ),
    .out(\a_lt_b$in1 ),
    .reset(reset)
  );
  ZeroComparator_0x422b1f52edd46a85 b_zero (
    .clk(clk),
    .in_(\a_lt_b$in1 ),
    .out(\b_zero$out ),
    .reset(reset)
  );
  Subtractor_0x422b1f52edd46a85 sub (
    .clk(clk),
    .in0(\a_lt_b$in0 ),
    .in1(\a_lt_b$in1 ),
    .out(\a_mux$in_$001 ),
    .reset(reset)
  );
  assign \a_lt_b$clk  = clk;
  assign \a_lt_b$reset  = reset;
  assign \a_mux$clk  = clk;
  assign \a_mux$in_$000  = req_msg_a;
  assign \a_mux$in_$002  = \a_lt_b$in1 ;
  assign \a_mux$reset  = reset;
  assign \a_mux$sel  = a_mux_sel;
  assign \a_reg$clk  = clk;
  assign \a_reg$en  = a_reg_en;
  assign \a_reg$in_  = \a_mux$out ;
  assign \a_reg$out  = \a_lt_b$in0 ;
  assign \a_reg$reset  = reset;
  assign \b_mux$clk  = clk;
  assign \b_mux$in_$000  = \a_lt_b$in0 ;
  assign \b_mux$in_$001  = req_msg_b;
  assign \b_mux$reset  = reset;
  assign \b_mux$sel  = b_mux_sel;
  assign \b_reg$clk  = clk;
  assign \b_reg$en  = b_reg_en;
  assign \b_reg$in_  = \b_mux$out ;
  assign \b_reg$out  = \a_lt_b$in1 ;
  assign \b_reg$reset  = reset;
  assign b_reg_out = \a_lt_b$in1 ;
  assign \b_zero$clk  = clk;
  assign \b_zero$in_  = \a_lt_b$in1 ;
  assign \b_zero$reset  = reset;
  assign is_a_lt_b = \a_lt_b$out ;
  assign is_b_zero = \b_zero$out ;
  assign resp_msg = \a_mux$in_$001 ;
  assign \sub$clk  = clk;
  assign \sub$in0  = \a_lt_b$in0 ;
  assign \sub$in1  = \a_lt_b$in1 ;
  assign \sub$out  = \a_mux$in_$001 ;
  assign \sub$reset  = reset;
  assign sub_out = \a_mux$in_$001 ;
endmodule

module LtComparator_0x422b1f52edd46a85(clk, in0, in1, out, reset);
  input [0:0] clk;
  wire [0:0] clk;
  input [15:0] in0;
  wire [15:0] in0;
  input [15:0] in1;
  wire [15:0] in1;
  output [0:0] out;
  wire [0:0] out;
  input [0:0] reset;
  wire [0:0] reset;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  sg13g2_inv_1 _050_ (
    .A(in0[14]),
    .Y(_000_)
  );
  sg13g2_inv_1 _051_ (
    .A(in0[13]),
    .Y(_001_)
  );
  sg13g2_inv_1 _052_ (
    .A(in0[11]),
    .Y(_002_)
  );
  sg13g2_inv_1 _053_ (
    .A(in0[10]),
    .Y(_003_)
  );
  sg13g2_inv_1 _054_ (
    .A(in1[9]),
    .Y(_004_)
  );
  sg13g2_inv_1 _055_ (
    .A(in1[8]),
    .Y(_005_)
  );
  sg13g2_inv_1 _056_ (
    .A(in0[7]),
    .Y(_006_)
  );
  sg13g2_inv_1 _057_ (
    .A(in0[4]),
    .Y(_007_)
  );
  sg13g2_nand2b_1 _058_ (
    .A_N(in0[6]),
    .B(in1[6]),
    .Y(_008_)
  );
  sg13g2_nand2b_1 _059_ (
    .A_N(in1[5]),
    .B(in0[5]),
    .Y(_009_)
  );
  sg13g2_nand2b_1 _060_ (
    .A_N(in1[1]),
    .B(in0[1]),
    .Y(_010_)
  );
  sg13g2_nand3b_1 _061_ (
    .A_N(in0[0]),
    .B(_010_),
    .C(in1[0]),
    .Y(_011_)
  );
  sg13g2_nor2b_1 _062_ (
    .A(in0[3]),
    .B_N(in1[3]),
    .Y(_012_)
  );
  sg13g2_nand2b_1 _063_ (
    .A_N(in0[3]),
    .B(in1[3]),
    .Y(_013_)
  );
  sg13g2_nor2b_1 _064_ (
    .A(in1[2]),
    .B_N(in0[2]),
    .Y(_014_)
  );
  sg13g2_nor2b_1 _065_ (
    .A(in0[1]),
    .B_N(in1[1]),
    .Y(_015_)
  );
  sg13g2_nor2b_1 _066_ (
    .A(in0[2]),
    .B_N(in1[2]),
    .Y(_016_)
  );
  sg13g2_nor4_1 _067_ (
    .A(_012_),
    .B(_014_),
    .C(_015_),
    .D(_016_),
    .Y(_017_)
  );
  sg13g2_nand2b_1 _068_ (
    .A_N(in1[3]),
    .B(in0[3]),
    .Y(_018_)
  );
  sg13g2_o21ai_1 _069_ (
    .A1(_007_),
    .A2(in1[4]),
    .B1(_018_),
    .Y(_019_)
  );
  sg13g2_a221oi_1 _070_ (
    .A1(_013_),
    .A2(_014_),
    .B1(_017_),
    .B2(_011_),
    .C1(_019_),
    .Y(_020_)
  );
  sg13g2_nor2b_1 _071_ (
    .A(in0[5]),
    .B_N(in1[5]),
    .Y(_021_)
  );
  sg13g2_a21o_1 _072_ (
    .A1(_007_),
    .A2(in1[4]),
    .B1(_021_),
    .X(_022_)
  );
  sg13g2_o21ai_1 _073_ (
    .A1(_020_),
    .A2(_022_),
    .B1(_009_),
    .Y(_023_)
  );
  sg13g2_nand2b_1 _074_ (
    .A_N(in1[6]),
    .B(in0[6]),
    .Y(_024_)
  );
  sg13g2_o21ai_1 _075_ (
    .A1(in1[7]),
    .A2(_006_),
    .B1(_024_),
    .Y(_025_)
  );
  sg13g2_a21oi_1 _076_ (
    .A1(_008_),
    .A2(_023_),
    .B1(_025_),
    .Y(_026_)
  );
  sg13g2_nand2_1 _077_ (
    .A(in1[7]),
    .B(_006_),
    .Y(_027_)
  );
  sg13g2_o21ai_1 _078_ (
    .A1(in0[8]),
    .A2(_005_),
    .B1(_027_),
    .Y(_028_)
  );
  sg13g2_a22oi_1 _079_ (
    .A1(_004_),
    .A2(in0[9]),
    .B1(in0[8]),
    .B2(_005_),
    .Y(_029_)
  );
  sg13g2_o21ai_1 _080_ (
    .A1(_026_),
    .A2(_028_),
    .B1(_029_),
    .Y(_030_)
  );
  sg13g2_nand2_1 _081_ (
    .A(in1[11]),
    .B(_002_),
    .Y(_031_)
  );
  sg13g2_o21ai_1 _082_ (
    .A1(_004_),
    .A2(in0[9]),
    .B1(_031_),
    .Y(_032_)
  );
  sg13g2_a21oi_1 _083_ (
    .A1(in1[10]),
    .A2(_003_),
    .B1(_032_),
    .Y(_033_)
  );
  sg13g2_nand2b_1 _084_ (
    .A_N(in1[10]),
    .B(in0[10]),
    .Y(_034_)
  );
  sg13g2_o21ai_1 _085_ (
    .A1(in1[11]),
    .A2(_002_),
    .B1(_034_),
    .Y(_035_)
  );
  sg13g2_a21o_1 _086_ (
    .A1(_030_),
    .A2(_033_),
    .B1(_035_),
    .X(_036_)
  );
  sg13g2_nand2b_1 _087_ (
    .A_N(in0[15]),
    .B(in1[15]),
    .Y(_037_)
  );
  sg13g2_nand2b_1 _088_ (
    .A_N(in1[15]),
    .B(in0[15]),
    .Y(_038_)
  );
  sg13g2_xnor2_1 _089_ (
    .A(in1[14]),
    .B(in0[14]),
    .Y(_039_)
  );
  sg13g2_nand3_1 _090_ (
    .A(_037_),
    .B(_038_),
    .C(_039_),
    .Y(_040_)
  );
  sg13g2_nand2b_1 _091_ (
    .A_N(in1[12]),
    .B(in0[12]),
    .Y(_041_)
  );
  sg13g2_o21ai_1 _092_ (
    .A1(in1[13]),
    .A2(_001_),
    .B1(_041_),
    .Y(_042_)
  );
  sg13g2_nand2_1 _093_ (
    .A(in1[13]),
    .B(_001_),
    .Y(_043_)
  );
  sg13g2_nor2b_1 _094_ (
    .A(in0[12]),
    .B_N(in1[12]),
    .Y(_044_)
  );
  sg13g2_o21ai_1 _095_ (
    .A1(_031_),
    .A2(_034_),
    .B1(_043_),
    .Y(_045_)
  );
  sg13g2_nor4_1 _096_ (
    .A(_040_),
    .B(_042_),
    .C(_044_),
    .D(_045_),
    .Y(_046_)
  );
  sg13g2_nand2_1 _097_ (
    .A(_042_),
    .B(_043_),
    .Y(_047_)
  );
  sg13g2_nor2_1 _098_ (
    .A(_040_),
    .B(_047_),
    .Y(_048_)
  );
  sg13g2_o21ai_1 _099_ (
    .A1(in1[14]),
    .A2(_000_),
    .B1(_038_),
    .Y(_049_)
  );
  sg13g2_a221oi_1 _100_ (
    .A1(_036_),
    .A2(_046_),
    .B1(_049_),
    .B2(_037_),
    .C1(_048_),
    .Y(out)
  );
endmodule

module Mux_0x683fa1a418b072c9(clk, \in_$000 , \in_$001 , \in_$002 , out, reset, sel);
  input [0:0] clk;
  wire [0:0] clk;
  input [15:0] \in_$000 ;
  wire [15:0] \in_$000 ;
  input [15:0] \in_$001 ;
  wire [15:0] \in_$001 ;
  input [15:0] \in_$002 ;
  wire [15:0] \in_$002 ;
  output [15:0] out;
  wire [15:0] out;
  input [0:0] reset;
  wire [0:0] reset;
  input [1:0] sel;
  wire [1:0] sel;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire [15:0] \in_[0] ;
  wire [15:0] \in_[1] ;
  wire [15:0] \in_[2] ;
  sg13g2_nor2b_1 _35_ (
    .A(sel[1]),
    .B_N(sel[0]),
    .Y(_12_)
  );
  sg13g2_nor2b_1 _36_ (
    .A(sel[0]),
    .B_N(sel[1]),
    .Y(_13_)
  );
  sg13g2_xnor2_1 _37_ (
    .A(sel[0]),
    .B(sel[1]),
    .Y(_14_)
  );
  sg13g2_nand2_1 _38_ (
    .A(\in_$000 [0]),
    .B(_14_),
    .Y(_15_)
  );
  sg13g2_a22oi_1 _39_ (
    .A1(\in_$001 [0]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [0]),
    .Y(_16_)
  );
  sg13g2_nand2_1 _40_ (
    .A(_15_),
    .B(_16_),
    .Y(out[0])
  );
  sg13g2_nand2_1 _41_ (
    .A(\in_$000 [1]),
    .B(_14_),
    .Y(_17_)
  );
  sg13g2_a22oi_1 _42_ (
    .A1(\in_$001 [1]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [1]),
    .Y(_18_)
  );
  sg13g2_nand2_1 _43_ (
    .A(_17_),
    .B(_18_),
    .Y(out[1])
  );
  sg13g2_nand2_1 _44_ (
    .A(\in_$000 [2]),
    .B(_14_),
    .Y(_19_)
  );
  sg13g2_a22oi_1 _45_ (
    .A1(\in_$001 [2]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [2]),
    .Y(_20_)
  );
  sg13g2_nand2_1 _46_ (
    .A(_19_),
    .B(_20_),
    .Y(out[2])
  );
  sg13g2_nand2_1 _47_ (
    .A(\in_$000 [3]),
    .B(_14_),
    .Y(_21_)
  );
  sg13g2_a22oi_1 _48_ (
    .A1(\in_$001 [3]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [3]),
    .Y(_22_)
  );
  sg13g2_nand2_1 _49_ (
    .A(_21_),
    .B(_22_),
    .Y(out[3])
  );
  sg13g2_nand2_1 _50_ (
    .A(\in_$000 [4]),
    .B(_14_),
    .Y(_23_)
  );
  sg13g2_a22oi_1 _51_ (
    .A1(\in_$001 [4]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [4]),
    .Y(_24_)
  );
  sg13g2_nand2_1 _52_ (
    .A(_23_),
    .B(_24_),
    .Y(out[4])
  );
  sg13g2_nand2_1 _53_ (
    .A(\in_$000 [5]),
    .B(_14_),
    .Y(_25_)
  );
  sg13g2_a22oi_1 _54_ (
    .A1(\in_$001 [5]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [5]),
    .Y(_26_)
  );
  sg13g2_nand2_1 _55_ (
    .A(_25_),
    .B(_26_),
    .Y(out[5])
  );
  sg13g2_nand2_1 _56_ (
    .A(\in_$000 [6]),
    .B(_14_),
    .Y(_27_)
  );
  sg13g2_a22oi_1 _57_ (
    .A1(\in_$001 [6]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [6]),
    .Y(_28_)
  );
  sg13g2_nand2_1 _58_ (
    .A(_27_),
    .B(_28_),
    .Y(out[6])
  );
  sg13g2_nand2_1 _59_ (
    .A(\in_$000 [7]),
    .B(_14_),
    .Y(_29_)
  );
  sg13g2_a22oi_1 _60_ (
    .A1(\in_$001 [7]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [7]),
    .Y(_30_)
  );
  sg13g2_nand2_1 _61_ (
    .A(_29_),
    .B(_30_),
    .Y(out[7])
  );
  sg13g2_nand2_1 _62_ (
    .A(\in_$000 [8]),
    .B(_14_),
    .Y(_31_)
  );
  sg13g2_a22oi_1 _63_ (
    .A1(\in_$001 [8]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [8]),
    .Y(_32_)
  );
  sg13g2_nand2_1 _64_ (
    .A(_31_),
    .B(_32_),
    .Y(out[8])
  );
  sg13g2_nand2_1 _65_ (
    .A(\in_$000 [9]),
    .B(_14_),
    .Y(_33_)
  );
  sg13g2_a22oi_1 _66_ (
    .A1(\in_$001 [9]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [9]),
    .Y(_34_)
  );
  sg13g2_nand2_1 _67_ (
    .A(_33_),
    .B(_34_),
    .Y(out[9])
  );
  sg13g2_nand2_1 _68_ (
    .A(\in_$000 [10]),
    .B(_14_),
    .Y(_00_)
  );
  sg13g2_a22oi_1 _69_ (
    .A1(\in_$001 [10]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [10]),
    .Y(_01_)
  );
  sg13g2_nand2_1 _70_ (
    .A(_00_),
    .B(_01_),
    .Y(out[10])
  );
  sg13g2_nand2_1 _71_ (
    .A(\in_$000 [11]),
    .B(_14_),
    .Y(_02_)
  );
  sg13g2_a22oi_1 _72_ (
    .A1(\in_$001 [11]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [11]),
    .Y(_03_)
  );
  sg13g2_nand2_1 _73_ (
    .A(_02_),
    .B(_03_),
    .Y(out[11])
  );
  sg13g2_nand2_1 _74_ (
    .A(\in_$000 [12]),
    .B(_14_),
    .Y(_04_)
  );
  sg13g2_a22oi_1 _75_ (
    .A1(\in_$001 [12]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [12]),
    .Y(_05_)
  );
  sg13g2_nand2_1 _76_ (
    .A(_04_),
    .B(_05_),
    .Y(out[12])
  );
  sg13g2_nand2_1 _77_ (
    .A(\in_$000 [13]),
    .B(_14_),
    .Y(_06_)
  );
  sg13g2_a22oi_1 _78_ (
    .A1(\in_$001 [13]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [13]),
    .Y(_07_)
  );
  sg13g2_nand2_1 _79_ (
    .A(_06_),
    .B(_07_),
    .Y(out[13])
  );
  sg13g2_nand2_1 _80_ (
    .A(\in_$000 [14]),
    .B(_14_),
    .Y(_08_)
  );
  sg13g2_a22oi_1 _81_ (
    .A1(\in_$001 [14]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [14]),
    .Y(_09_)
  );
  sg13g2_nand2_1 _82_ (
    .A(_08_),
    .B(_09_),
    .Y(out[14])
  );
  sg13g2_nand2_1 _83_ (
    .A(\in_$000 [15]),
    .B(_14_),
    .Y(_10_)
  );
  sg13g2_a22oi_1 _84_ (
    .A1(\in_$001 [15]),
    .A2(_12_),
    .B1(_13_),
    .B2(\in_$002 [15]),
    .Y(_11_)
  );
  sg13g2_nand2_1 _85_ (
    .A(_10_),
    .B(_11_),
    .Y(out[15])
  );
  assign \in_[0]  = \in_$000 ;
  assign \in_[1]  = \in_$001 ;
  assign \in_[2]  = \in_$002 ;
endmodule

module Mux_0xdd6473406d1a99a(clk, \in_$000 , \in_$001 , out, reset, sel);
  input [0:0] clk;
  wire [0:0] clk;
  input [15:0] \in_$000 ;
  wire [15:0] \in_$000 ;
  input [15:0] \in_$001 ;
  wire [15:0] \in_$001 ;
  output [15:0] out;
  wire [15:0] out;
  input [0:0] reset;
  wire [0:0] reset;
  input [0:0] sel;
  wire [0:0] sel;
  wire [15:0] \in_[0] ;
  wire [15:0] \in_[1] ;
  sg13g2_mux2_1 _00_ (
    .A0(\in_$000 [0]),
    .A1(\in_$001 [0]),
    .S(sel),
    .X(out[0])
  );
  sg13g2_mux2_1 _01_ (
    .A0(\in_$000 [1]),
    .A1(\in_$001 [1]),
    .S(sel),
    .X(out[1])
  );
  sg13g2_mux2_1 _02_ (
    .A0(\in_$000 [2]),
    .A1(\in_$001 [2]),
    .S(sel),
    .X(out[2])
  );
  sg13g2_mux2_1 _03_ (
    .A0(\in_$000 [3]),
    .A1(\in_$001 [3]),
    .S(sel),
    .X(out[3])
  );
  sg13g2_mux2_1 _04_ (
    .A0(\in_$000 [4]),
    .A1(\in_$001 [4]),
    .S(sel),
    .X(out[4])
  );
  sg13g2_mux2_1 _05_ (
    .A0(\in_$000 [5]),
    .A1(\in_$001 [5]),
    .S(sel),
    .X(out[5])
  );
  sg13g2_mux2_1 _06_ (
    .A0(\in_$000 [6]),
    .A1(\in_$001 [6]),
    .S(sel),
    .X(out[6])
  );
  sg13g2_mux2_1 _07_ (
    .A0(\in_$000 [7]),
    .A1(\in_$001 [7]),
    .S(sel),
    .X(out[7])
  );
  sg13g2_mux2_1 _08_ (
    .A0(\in_$000 [8]),
    .A1(\in_$001 [8]),
    .S(sel),
    .X(out[8])
  );
  sg13g2_mux2_1 _09_ (
    .A0(\in_$000 [9]),
    .A1(\in_$001 [9]),
    .S(sel),
    .X(out[9])
  );
  sg13g2_mux2_1 _10_ (
    .A0(\in_$000 [10]),
    .A1(\in_$001 [10]),
    .S(sel),
    .X(out[10])
  );
  sg13g2_mux2_1 _11_ (
    .A0(\in_$000 [11]),
    .A1(\in_$001 [11]),
    .S(sel),
    .X(out[11])
  );
  sg13g2_mux2_1 _12_ (
    .A0(\in_$000 [12]),
    .A1(\in_$001 [12]),
    .S(sel),
    .X(out[12])
  );
  sg13g2_mux2_1 _13_ (
    .A0(\in_$000 [13]),
    .A1(\in_$001 [13]),
    .S(sel),
    .X(out[13])
  );
  sg13g2_mux2_1 _14_ (
    .A0(\in_$000 [14]),
    .A1(\in_$001 [14]),
    .S(sel),
    .X(out[14])
  );
  sg13g2_mux2_1 _15_ (
    .A0(\in_$000 [15]),
    .A1(\in_$001 [15]),
    .S(sel),
    .X(out[15])
  );
  assign \in_[0]  = \in_$000 ;
  assign \in_[1]  = \in_$001 ;
endmodule

module RegEn_0x68db79c4ec1d6e5b(clk, en, in_, out, reset);
  input [0:0] clk;
  wire [0:0] clk;
  input [0:0] en;
  wire [0:0] en;
  input [15:0] in_;
  wire [15:0] in_;
  output [15:0] out;
  wire [15:0] out;
  input [0:0] reset;
  wire [0:0] reset;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  sg13g2_mux2_1 _16_ (
    .A0(out[0]),
    .A1(in_[0]),
    .S(en),
    .X(_00_)
  );
  sg13g2_mux2_1 _17_ (
    .A0(out[1]),
    .A1(in_[1]),
    .S(en),
    .X(_01_)
  );
  sg13g2_mux2_1 _18_ (
    .A0(out[2]),
    .A1(in_[2]),
    .S(en),
    .X(_02_)
  );
  sg13g2_mux2_1 _19_ (
    .A0(out[3]),
    .A1(in_[3]),
    .S(en),
    .X(_03_)
  );
  sg13g2_mux2_1 _20_ (
    .A0(out[4]),
    .A1(in_[4]),
    .S(en),
    .X(_04_)
  );
  sg13g2_mux2_1 _21_ (
    .A0(out[5]),
    .A1(in_[5]),
    .S(en),
    .X(_05_)
  );
  sg13g2_mux2_1 _22_ (
    .A0(out[6]),
    .A1(in_[6]),
    .S(en),
    .X(_06_)
  );
  sg13g2_mux2_1 _23_ (
    .A0(out[7]),
    .A1(in_[7]),
    .S(en),
    .X(_07_)
  );
  sg13g2_mux2_1 _24_ (
    .A0(out[8]),
    .A1(in_[8]),
    .S(en),
    .X(_08_)
  );
  sg13g2_mux2_1 _25_ (
    .A0(out[9]),
    .A1(in_[9]),
    .S(en),
    .X(_09_)
  );
  sg13g2_mux2_1 _26_ (
    .A0(out[10]),
    .A1(in_[10]),
    .S(en),
    .X(_10_)
  );
  sg13g2_mux2_1 _27_ (
    .A0(out[11]),
    .A1(in_[11]),
    .S(en),
    .X(_11_)
  );
  sg13g2_mux2_1 _28_ (
    .A0(out[12]),
    .A1(in_[12]),
    .S(en),
    .X(_12_)
  );
  sg13g2_mux2_1 _29_ (
    .A0(out[13]),
    .A1(in_[13]),
    .S(en),
    .X(_13_)
  );
  sg13g2_mux2_1 _30_ (
    .A0(out[14]),
    .A1(in_[14]),
    .S(en),
    .X(_14_)
  );
  sg13g2_mux2_1 _31_ (
    .A0(out[15]),
    .A1(in_[15]),
    .S(en),
    .X(_15_)
  );
  sg13g2_dfrbpq_1 _32_ (
    .CLK(clk),
    .D(_00_),
    .Q(out[0]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _33_ (
    .CLK(clk),
    .D(_01_),
    .Q(out[1]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _34_ (
    .CLK(clk),
    .D(_02_),
    .Q(out[2]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _35_ (
    .CLK(clk),
    .D(_03_),
    .Q(out[3]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _36_ (
    .CLK(clk),
    .D(_04_),
    .Q(out[4]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _37_ (
    .CLK(clk),
    .D(_05_),
    .Q(out[5]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _38_ (
    .CLK(clk),
    .D(_06_),
    .Q(out[6]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _39_ (
    .CLK(clk),
    .D(_07_),
    .Q(out[7]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _40_ (
    .CLK(clk),
    .D(_08_),
    .Q(out[8]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _41_ (
    .CLK(clk),
    .D(_09_),
    .Q(out[9]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _42_ (
    .CLK(clk),
    .D(_10_),
    .Q(out[10]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _43_ (
    .CLK(clk),
    .D(_11_),
    .Q(out[11]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _44_ (
    .CLK(clk),
    .D(_12_),
    .Q(out[12]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _45_ (
    .CLK(clk),
    .D(_13_),
    .Q(out[13]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _46_ (
    .CLK(clk),
    .D(_14_),
    .Q(out[14]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _47_ (
    .CLK(clk),
    .D(_15_),
    .Q(out[15]),
    .RESET_B(1'h1)
  );
endmodule

module RegRst_0x9f365fdf6c8998a(clk, in_, out, reset);
  input [0:0] clk;
  wire [0:0] clk;
  input [1:0] in_;
  wire [1:0] in_;
  output [1:0] out;
  wire [1:0] out;
  input [0:0] reset;
  wire [0:0] reset;
  wire _0_;
  wire _1_;
  sg13g2_nor2b_1 _2_ (
    .A(reset),
    .B_N(in_[0]),
    .Y(_0_)
  );
  sg13g2_nor2b_1 _3_ (
    .A(reset),
    .B_N(in_[1]),
    .Y(_1_)
  );
  sg13g2_dfrbpq_1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(out[0]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _5_ (
    .CLK(clk),
    .D(_1_),
    .Q(out[1]),
    .RESET_B(1'h1)
  );
endmodule

module Subtractor_0x422b1f52edd46a85(clk, in0, in1, out, reset);
  input [0:0] clk;
  wire [0:0] clk;
  input [15:0] in0;
  wire [15:0] in0;
  input [15:0] in1;
  wire [15:0] in1;
  output [15:0] out;
  wire [15:0] out;
  input [0:0] reset;
  wire [0:0] reset;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  sg13g2_inv_1 _061_ (
    .A(in1[3]),
    .Y(_020_)
  );
  sg13g2_inv_1 _062_ (
    .A(in1[14]),
    .Y(_021_)
  );
  sg13g2_nor2b_1 _063_ (
    .A(in0[0]),
    .B_N(in1[0]),
    .Y(_022_)
  );
  sg13g2_xor2_1 _064_ (
    .A(in1[0]),
    .B(in0[0]),
    .X(out[0])
  );
  sg13g2_nand2b_1 _065_ (
    .A_N(in1[1]),
    .B(in0[1]),
    .Y(_023_)
  );
  sg13g2_nor2b_1 _066_ (
    .A(in0[1]),
    .B_N(in1[1]),
    .Y(_024_)
  );
  sg13g2_xnor2_1 _067_ (
    .A(in1[1]),
    .B(in0[1]),
    .Y(_025_)
  );
  sg13g2_xnor2_1 _068_ (
    .A(_022_),
    .B(_025_),
    .Y(out[1])
  );
  sg13g2_o21ai_1 _069_ (
    .A1(_022_),
    .A2(_024_),
    .B1(_023_),
    .Y(_026_)
  );
  sg13g2_nor2b_1 _070_ (
    .A(in1[2]),
    .B_N(in0[2]),
    .Y(_027_)
  );
  sg13g2_xnor2_1 _071_ (
    .A(in1[2]),
    .B(in0[2]),
    .Y(_028_)
  );
  sg13g2_xor2_1 _072_ (
    .A(_026_),
    .B(_028_),
    .X(out[2])
  );
  sg13g2_a21oi_1 _073_ (
    .A1(_026_),
    .A2(_028_),
    .B1(_027_),
    .Y(_029_)
  );
  sg13g2_nor2_1 _074_ (
    .A(_020_),
    .B(in0[3]),
    .Y(_030_)
  );
  sg13g2_xnor2_1 _075_ (
    .A(in1[3]),
    .B(in0[3]),
    .Y(_031_)
  );
  sg13g2_xnor2_1 _076_ (
    .A(_029_),
    .B(_031_),
    .Y(out[3])
  );
  sg13g2_nor2b_1 _077_ (
    .A(in1[4]),
    .B_N(in0[4]),
    .Y(_032_)
  );
  sg13g2_xor2_1 _078_ (
    .A(in1[4]),
    .B(in0[4]),
    .X(_033_)
  );
  sg13g2_a221oi_1 _079_ (
    .A1(_020_),
    .A2(in0[3]),
    .B1(_026_),
    .B2(_028_),
    .C1(_027_),
    .Y(_034_)
  );
  sg13g2_nor3_1 _080_ (
    .A(_030_),
    .B(_033_),
    .C(_034_),
    .Y(_035_)
  );
  sg13g2_o21ai_1 _081_ (
    .A1(_030_),
    .A2(_034_),
    .B1(_033_),
    .Y(_036_)
  );
  sg13g2_nor2b_1 _082_ (
    .A(_035_),
    .B_N(_036_),
    .Y(out[4])
  );
  sg13g2_nand2b_1 _083_ (
    .A_N(in1[5]),
    .B(in0[5]),
    .Y(_037_)
  );
  sg13g2_xnor2_1 _084_ (
    .A(in1[5]),
    .B(in0[5]),
    .Y(_038_)
  );
  sg13g2_o21ai_1 _085_ (
    .A1(_032_),
    .A2(_035_),
    .B1(_038_),
    .Y(_039_)
  );
  sg13g2_or3_1 _086_ (
    .A(_032_),
    .B(_035_),
    .C(_038_),
    .X(_040_)
  );
  sg13g2_and2_1 _087_ (
    .A(_039_),
    .B(_040_),
    .X(out[5])
  );
  sg13g2_nor2b_1 _088_ (
    .A(in1[6]),
    .B_N(in0[6]),
    .Y(_041_)
  );
  sg13g2_xor2_1 _089_ (
    .A(in1[6]),
    .B(in0[6]),
    .X(_042_)
  );
  sg13g2_a21oi_1 _090_ (
    .A1(_037_),
    .A2(_039_),
    .B1(_042_),
    .Y(_043_)
  );
  sg13g2_nand3_1 _091_ (
    .A(_037_),
    .B(_039_),
    .C(_042_),
    .Y(_044_)
  );
  sg13g2_nor2b_1 _092_ (
    .A(_043_),
    .B_N(_044_),
    .Y(out[6])
  );
  sg13g2_nor2_1 _093_ (
    .A(_041_),
    .B(_043_),
    .Y(_045_)
  );
  sg13g2_nor2b_1 _094_ (
    .A(in1[7]),
    .B_N(in0[7]),
    .Y(_046_)
  );
  sg13g2_nor2b_1 _095_ (
    .A(in0[7]),
    .B_N(in1[7]),
    .Y(_047_)
  );
  sg13g2_nor2_1 _096_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  sg13g2_xnor2_1 _097_ (
    .A(_045_),
    .B(_048_),
    .Y(out[7])
  );
  sg13g2_nor2b_1 _098_ (
    .A(in1[8]),
    .B_N(in0[8]),
    .Y(_049_)
  );
  sg13g2_xor2_1 _099_ (
    .A(in1[8]),
    .B(in0[8]),
    .X(_050_)
  );
  sg13g2_nor3_1 _100_ (
    .A(_041_),
    .B(_043_),
    .C(_046_),
    .Y(_051_)
  );
  sg13g2_nor3_1 _101_ (
    .A(_047_),
    .B(_050_),
    .C(_051_),
    .Y(_052_)
  );
  sg13g2_o21ai_1 _102_ (
    .A1(_047_),
    .A2(_051_),
    .B1(_050_),
    .Y(_053_)
  );
  sg13g2_nor2b_1 _103_ (
    .A(_052_),
    .B_N(_053_),
    .Y(out[8])
  );
  sg13g2_nor2_1 _104_ (
    .A(_049_),
    .B(_052_),
    .Y(_054_)
  );
  sg13g2_nor2b_1 _105_ (
    .A(in1[9]),
    .B_N(in0[9]),
    .Y(_055_)
  );
  sg13g2_nor2b_1 _106_ (
    .A(in0[9]),
    .B_N(in1[9]),
    .Y(_056_)
  );
  sg13g2_nor2_1 _107_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  sg13g2_xnor2_1 _108_ (
    .A(_054_),
    .B(_057_),
    .Y(out[9])
  );
  sg13g2_nor2b_1 _109_ (
    .A(in1[10]),
    .B_N(in0[10]),
    .Y(_058_)
  );
  sg13g2_xor2_1 _110_ (
    .A(in1[10]),
    .B(in0[10]),
    .X(_059_)
  );
  sg13g2_nor3_1 _111_ (
    .A(_049_),
    .B(_052_),
    .C(_055_),
    .Y(_060_)
  );
  sg13g2_nor3_1 _112_ (
    .A(_056_),
    .B(_059_),
    .C(_060_),
    .Y(_000_)
  );
  sg13g2_o21ai_1 _113_ (
    .A1(_056_),
    .A2(_060_),
    .B1(_059_),
    .Y(_001_)
  );
  sg13g2_nor2b_1 _114_ (
    .A(_000_),
    .B_N(_001_),
    .Y(out[10])
  );
  sg13g2_nor2_1 _115_ (
    .A(_058_),
    .B(_000_),
    .Y(_002_)
  );
  sg13g2_nor2b_1 _116_ (
    .A(in1[11]),
    .B_N(in0[11]),
    .Y(_003_)
  );
  sg13g2_nor2b_1 _117_ (
    .A(in0[11]),
    .B_N(in1[11]),
    .Y(_004_)
  );
  sg13g2_nor2_1 _118_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  sg13g2_xnor2_1 _119_ (
    .A(_002_),
    .B(_005_),
    .Y(out[11])
  );
  sg13g2_nor2b_1 _120_ (
    .A(in1[12]),
    .B_N(in0[12]),
    .Y(_006_)
  );
  sg13g2_xor2_1 _121_ (
    .A(in1[12]),
    .B(in0[12]),
    .X(_007_)
  );
  sg13g2_nor3_1 _122_ (
    .A(_058_),
    .B(_000_),
    .C(_003_),
    .Y(_008_)
  );
  sg13g2_nor3_1 _123_ (
    .A(_004_),
    .B(_007_),
    .C(_008_),
    .Y(_009_)
  );
  sg13g2_o21ai_1 _124_ (
    .A1(_004_),
    .A2(_008_),
    .B1(_007_),
    .Y(_010_)
  );
  sg13g2_nor2b_1 _125_ (
    .A(_009_),
    .B_N(_010_),
    .Y(out[12])
  );
  sg13g2_nand2b_1 _126_ (
    .A_N(in1[13]),
    .B(in0[13]),
    .Y(_011_)
  );
  sg13g2_xnor2_1 _127_ (
    .A(in1[13]),
    .B(in0[13]),
    .Y(_012_)
  );
  sg13g2_o21ai_1 _128_ (
    .A1(_006_),
    .A2(_009_),
    .B1(_012_),
    .Y(_013_)
  );
  sg13g2_or3_1 _129_ (
    .A(_006_),
    .B(_009_),
    .C(_012_),
    .X(_014_)
  );
  sg13g2_and2_1 _130_ (
    .A(_013_),
    .B(_014_),
    .X(out[13])
  );
  sg13g2_xor2_1 _131_ (
    .A(in1[14]),
    .B(in0[14]),
    .X(_015_)
  );
  sg13g2_a21oi_1 _132_ (
    .A1(_011_),
    .A2(_013_),
    .B1(_015_),
    .Y(_016_)
  );
  sg13g2_nand3_1 _133_ (
    .A(_011_),
    .B(_013_),
    .C(_015_),
    .Y(_017_)
  );
  sg13g2_nor2b_1 _134_ (
    .A(_016_),
    .B_N(_017_),
    .Y(out[14])
  );
  sg13g2_a21oi_1 _135_ (
    .A1(_021_),
    .A2(in0[14]),
    .B1(_016_),
    .Y(_018_)
  );
  sg13g2_xnor2_1 _136_ (
    .A(in1[15]),
    .B(in0[15]),
    .Y(_019_)
  );
  sg13g2_xnor2_1 _137_ (
    .A(_018_),
    .B(_019_),
    .Y(out[15])
  );
endmodule

module ZeroComparator_0x422b1f52edd46a85(clk, in_, out, reset);
  input [0:0] clk;
  wire [0:0] clk;
  input [15:0] in_;
  wire [15:0] in_;
  output [0:0] out;
  wire [0:0] out;
  input [0:0] reset;
  wire [0:0] reset;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  sg13g2_nor3_1 _05_ (
    .A(in_[1]),
    .B(in_[2]),
    .C(in_[13]),
    .Y(_00_)
  );
  sg13g2_nor3_1 _06_ (
    .A(in_[8]),
    .B(in_[11]),
    .C(in_[14]),
    .Y(_01_)
  );
  sg13g2_nor4_1 _07_ (
    .A(in_[4]),
    .B(in_[7]),
    .C(in_[9]),
    .D(in_[10]),
    .Y(_02_)
  );
  sg13g2_nor4_1 _08_ (
    .A(in_[0]),
    .B(in_[5]),
    .C(in_[6]),
    .D(in_[15]),
    .Y(_03_)
  );
  sg13g2_nand4_1 _09_ (
    .A(_00_),
    .B(_01_),
    .C(_02_),
    .D(_03_),
    .Y(_04_)
  );
  sg13g2_nor3_1 _10_ (
    .A(in_[3]),
    .B(in_[12]),
    .C(_04_),
    .Y(out)
  );
endmodule

module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  input clk;
  wire clk;
  input [31:0] req_msg;
  wire [31:0] req_msg;
  output req_rdy;
  wire req_rdy;
  input req_val;
  wire req_val;
  input reset;
  wire reset;
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  input resp_rdy;
  wire resp_rdy;
  output resp_val;
  wire resp_val;
  wire [1:0] \ctrl$a_mux_sel ;
  wire [0:0] \ctrl$a_reg_en ;
  wire [0:0] \ctrl$b_mux_sel ;
  wire [0:0] \ctrl$b_reg_en ;
  wire [0:0] \ctrl$clk ;
  wire [0:0] \ctrl$is_a_lt_b ;
  wire [0:0] \ctrl$is_b_zero ;
  wire [0:0] \ctrl$req_rdy ;
  wire [0:0] \ctrl$req_val ;
  wire [0:0] \ctrl$reset ;
  wire [0:0] \ctrl$resp_rdy ;
  wire [0:0] \ctrl$resp_val ;
  wire [1:0] \dpath$a_mux_sel ;
  wire [0:0] \dpath$a_reg_en ;
  wire [0:0] \dpath$b_mux_sel ;
  wire [0:0] \dpath$b_reg_en ;
  wire [0:0] \dpath$clk ;
  wire [0:0] \dpath$is_a_lt_b ;
  wire [0:0] \dpath$is_b_zero ;
  wire [15:0] \dpath$req_msg_a ;
  wire [15:0] \dpath$req_msg_b ;
  wire [0:0] \dpath$reset ;
  wire [15:0] \dpath$resp_msg ;
  GcdUnitCtrlRTL_0x4d0fc71ead8d3d9e ctrl (
    .a_mux_sel(\ctrl$a_mux_sel ),
    .a_reg_en(\ctrl$a_reg_en ),
    .b_mux_sel(\ctrl$b_mux_sel ),
    .b_reg_en(\ctrl$b_reg_en ),
    .clk(clk),
    .is_a_lt_b(\ctrl$is_a_lt_b ),
    .is_b_zero(\ctrl$is_b_zero ),
    .req_rdy(\ctrl$req_rdy ),
    .req_val(req_val),
    .reset(reset),
    .resp_rdy(resp_rdy),
    .resp_val(\ctrl$resp_val )
  );
  GcdUnitDpathRTL_0x4d0fc71ead8d3d9e dpath (
    .a_mux_sel(\ctrl$a_mux_sel ),
    .a_reg_en(\ctrl$a_reg_en ),
    .b_mux_sel(\ctrl$b_mux_sel ),
    .b_reg_en(\ctrl$b_reg_en ),
    .clk(clk),
    .is_a_lt_b(\ctrl$is_a_lt_b ),
    .is_b_zero(\ctrl$is_b_zero ),
    .req_msg_a(req_msg[31:16]),
    .req_msg_b(req_msg[15:0]),
    .reset(reset),
    .resp_msg(\dpath$resp_msg )
  );
  assign \ctrl$clk  = clk;
  assign \ctrl$req_val  = req_val;
  assign \ctrl$reset  = reset;
  assign \ctrl$resp_rdy  = resp_rdy;
  assign \dpath$a_mux_sel  = \ctrl$a_mux_sel ;
  assign \dpath$a_reg_en  = \ctrl$a_reg_en ;
  assign \dpath$b_mux_sel  = \ctrl$b_mux_sel ;
  assign \dpath$b_reg_en  = \ctrl$b_reg_en ;
  assign \dpath$clk  = clk;
  assign \dpath$is_a_lt_b  = \ctrl$is_a_lt_b ;
  assign \dpath$is_b_zero  = \ctrl$is_b_zero ;
  assign \dpath$req_msg_a  = req_msg[31:16];
  assign \dpath$req_msg_b  = req_msg[15:0];
  assign \dpath$reset  = reset;
  assign req_rdy = \ctrl$req_rdy ;
  assign resp_msg = \dpath$resp_msg ;
  assign resp_val = \ctrl$resp_val ;
endmodule
