message(STATUS "############## CTS: START CMAKE ##############")

option(DEBUG_ICTS_SOURCE_DATA_MANAGER_CONFIG "source data manager config" OFF)
option(DEBUG_ICTS_SOURCE_DATA_MANAGER_DESIGN "source data manager design" OFF)
option(DEBUG_ICTS_SOURCE_DATA_MANAGER_IO "source data manager io" OFF)
option(DEBUG_ICTS_SOURCE_DATA_MANAGER_SPATIAL "source data manager spatial" OFF)
option(DEBUG_ICTS_SOURCE_DATA_MANAGER "source data manager" OFF)
option(DEBUG_ICTS_SOURCE_TOOLKIT_LOGGER "source toolkit logger" OFF)
option(DEBUG_ICTS_SOURCE_TOOLKIT_GEOMETRY "source toolkit geometry" OFF)
option(DEBUG_ICTS_SOURCE_TOOLKIT "source toolkit" OFF)
option(DEBUG_ICTS_SOURCE_MODULE_SYNTHESIS_REALIZATION "source module synthesis realization" OFF)
option(DEBUG_ICTS_SOURCE_MODULE_TOPOLOGY_KMEANS "source module topology kmeans" OFF)
option(DEBUG_ICTS_SOURCE_MODULE_TOPOLOGY_MCF "source module topology mcf" OFF)
option(DEBUG_ICTS_SOURCE_MODULE_TOPOLOGY_CLUSTERING "source module topology clustering" OFF)
option(DEBUG_ICTS_SOURCE_MODULE_TOPOLOGY "source module topology" OFF)
option(DEBUG_ICTS_SOURCE_MODULE "source module" OFF)
option(DEBUG_ICTS_SOURCE "source" OFF)
option(DEBUG_ICTS_INTERFACE "interface" OFF)
option(DEBUG_ICTS_TEST "test" OFF)

set(HOME_ICTS ${HOME_OPERATION}/iCTS)
set(ICTS_INTERFACE ${HOME_ICTS}/interface)
set(ICTS_SOURCE ${HOME_ICTS}/source)
set(ICTS_TEST ${HOME_ICTS}/test)

add_subdirectory(${ICTS_SOURCE})
add_subdirectory(${ICTS_INTERFACE})
add_subdirectory(${ICTS_TEST})

message(STATUS "############## CTS: END CMAKE ##############")
