set(ICTS_MODULE_SYNTHESIS_TRACE_DISTANCE ${ICTS_MODULE_SYNTHESIS_TRACE}/distance)
set(ICTS_MODULE_SYNTHESIS_TRACE_DOMAIN_STATUS ${ICTS_MODULE_SYNTHESIS_TRACE}/domain_status)
set(ICTS_MODULE_SYNTHESIS_TRACE_TOPOLOGY_BUILD ${ICTS_MODULE_SYNTHESIS_TRACE}/topology_build)

add_subdirectory(${ICTS_MODULE_SYNTHESIS_TRACE_DISTANCE})
add_subdirectory(${ICTS_MODULE_SYNTHESIS_TRACE_DOMAIN_STATUS})
add_subdirectory(${ICTS_MODULE_SYNTHESIS_TRACE_TOPOLOGY_BUILD})
